spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile:
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/ghma
      username: ghma
      password: ghma
      driver-class-name: org.mariadb.jdbc.Driver
  config:
    activate:
      on-profile: mysql